# Generated by Django 4.2.4 on 2023-12-20 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0006_jobseekerprofile_skills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobseekerprofile",
            old_name="profile_picture",
            new_name="profile_pic",
        ),
        migrations.RenameField(
            model_name="recruiterprofile",
            old_name="profile_picture",
            new_name="profile_pic",
        ),
    ]
