# Generated by Django 4.2.4 on 2023-12-20 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0007_rename_profile_picture_jobseekerprofile_profile_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobseekerprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recruiterprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
