# Generated by Django 4.2.4 on 2023-12-22 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0009_custom_user_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="profile_pic",
        ),
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="profile_pic",
        ),
    ]
