# Generated by Django 4.2.4 on 2023-12-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0010_remove_jobseekerprofile_profile_pic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="custom_user",
            name="about",
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
