# Generated by Django 4.2.6 on 2023-12-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0011_custom_user_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_model",
            name="update_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
